export const CONFIG = {
  AI_BASE_URL: 'http://localhost:20128',
  AI_AUTH_KEY: '', // Set your OmniRoute auth key here (or configure via Settings)
  SELECTOR_CONFIG_URL: 'http://localhost:20128/selectors.json',
  SELECTOR_REFRESH_HOURS: 6,
  AI_TIMEOUT_MS: 30000,
  AI_MAX_RETRIES: 1,
  DEFAULT_COOLDOWN_SECONDS: 30,
  DEFAULT_DAILY_CAP: 50,
  MAX_CONTENT_LIBRARY_ITEMS: 100,
  MAX_TOPIC_KEYWORDS: 20,
  MAX_TRACKED_ACCOUNTS: 10,
  MAX_MONITORED_POSTS: 3,
  MONITOR_INTERVAL_MINUTES: 5,
  MONITOR_DURATION_MINUTES: 60,
  MAX_POST_BUFFER_SIZE: 50,
  VOICE_PROFILE_MAX_CHARS: 1000,
} as const;
